<?php

/**
 * @link       https://wpali.com
 * @since      1.0.8
 *
 */

/**
 * The public-facing functionality of the pro plugin.
 *
 * @author     Ali Khallad <ali@wpali.com>
 */
if (!defined('ABSPATH')) {
	exit; // Exit if accessed directly
}

class Mega_Forms_Public_Pro
{

	private $plugin_name;
	private $version;

	/**
	 * Initialize the class and set its properties.
	 *
	 * @since    1.0.6
	 */
	public function __construct($plugin_name, $version)
	{
		$this->plugin_name = $plugin_name;
		$this->version = $version;
		$this->load_dependencies();
	}

	/**
	 * Load the required dependencies for this class.
	 *
	 * @since    1.0.6
	 */
	private function load_dependencies()
	{
		// Load Main Classes
		// require_once MEGAFORMS_DIR_PATH . '/pro/common/xxxxx.php';
	}

	/**
	 * Register the stylesheets for the public-facing side of the site.
	 *
	 * @since    1.0.0
	 */
	public function enqueue_styles()
	{
		/**
		 * Register the main CSS file for the frontend area (Pro).
		 * This file is automatically generated. It is a minified version of the following file:
		 * 
		 * - pro/common/assets/css/*.css
		 * - pro/public/assets/css/*.css
		 * 
		 * @see Gruntfile.js for more details
		 */
		wp_register_style('mf-public-pro', MEGAFORMS_DIR_URL . 'assets/pro/frontend/css/styles.min.css', array(), $this->version, 'all');

		if (mfget_option('load_form_styling', true)) {
			wp_enqueue_style('mf-public-pro');
		}
	}

	/**
	 * Register the JavaScript for the public-facing side of the site.
	 *
	 * @since    1.0.0
	 */
	public function enqueue_scripts()
	{
		/**
		 * Register the main JS file for the frontend area (Pro).
		 * This file is automatically generated. It is a minified version of the following file:
		 * 
		 * - pro/common/assets/js/*.js
		 * - pro/public/assets/js/*.js
		 * 
		 * @see Gruntfile.js for more details
		 */
		wp_register_script('mf-public-pro', MEGAFORMS_DIR_URL . 'assets/pro/frontend/js/scripts.min.js', array(), $this->version, false);


		// If reCaptcha is enabled, load recaptcha api script
		if (mfget_option('recaptcha_status', false)) {
			wp_print_script_tag(
				array(
					'id' => 'mf-recaptcha',
					'src' => esc_url('https://www.google.com/recaptcha/api.js'),
					'async' => true,
					'defer' => true
				)
			);
		}
	}

	/**
	 * Listen to form page submissions.
	 *
	 * @since    1.0.8
	 */
	public function listen()
	{
		// Handle paged form submissions
		if (isset($_POST['mform_next']) && isset($_POST['_mf_form_id']) && isset($_POST['_mf_current_page'])) {
			mf_submission()->exec(mfpost('_mf_form_id'), $_POST, 'page', array('page' => absint(mfpost('_mf_current_page'))));
		}

		// Handle save and continue action
		if (isset($_POST['mform_save']) && isset($_POST['_mf_form_id'])) {
			mf_submission()->exec(mfpost('_mf_form_id'), $_POST, 'save');
		}

		// Handle a download request
		if (isset($_GET['mf-dl'])) {
			mf_files()->maybe_process_download();
		}
	}
	/**
	 * Handle actions that should run before displaying the form markup.
	 *
	 * @since    1.0.8
	 */
	public function pre_form_display($form)
	{
		// Continue a submission if the current request has `mf_token` & `mf_hash`
		if (isset($_GET['mf_token']) && isset($_GET['mf_hash']) && mf_submission()->is_empty()) {
			$form_id = $_GET['mf_hash'] == wp_hash($form->ID) ? $form->ID : false;
			if ($form_id) {
				mf_submission()->exec($form_id, array(), 'continue');
			}
		}
	}
}
